[package]
name = "crate_test"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "A test crate"
authors = ["Cinob <cinob@foxmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
